GET http://127.0.0.1:5000/diaries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0NTBjYTVjMTY1ZTU1NTQ2Y2EwNmMiLCJpYXQiOjE2ODk1Mzg3OTMsImV4cCI6MTY5MDE0MzU5M30.KkiBhNFn9YLFbCj31ZaGtaAgLIqVWvF8kY8gO3Ee52U

###
GET http://127.0.0.1:5000/diaries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY


### Create Diary 1 ###
POST http://127.0.0.1:5000/diaries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY

{
  "title": "Diary 1",
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
}

### Create Diary 2 ###
POST http://127.0.0.1:5000/diaries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY

{
  "title": "Diary 2",
  "body": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem."
}

### Create Diary 3 ###
POST http://127.0.0.1:5000/diaries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY

{
  "title": "Diary 3",
  "body": "At vero eos et accusamus et iusto odio dignissimos."
}

### Create Diary 4 ###
POST http://127.0.0.1:5000/diaries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY

{
  "title": "Diary 4",
  "body": "Eaque ipsa quae ab illo inventore veritatis et quasi architecto."
}

### Create Diary 5 ###
POST http://127.0.0.1:5000/diaries/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MzA3YTJlMzJjY2FhYjM4NDIyMzkiLCJpYXQiOjE2ODk1MzI0NDIsImV4cCI6MTY5MDEzNzI0Mn0.bN3wd_ZJduUWoiHRCWZaZM_9kMqmUpuQu6iSZZkZPpY

{
  "title": "Diary 5",
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
}


###
# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0MmYzNDAzMmQ3OTU2YzcxM2JiODUiLCJpYXQiOjE2ODk1Mzg2MjksImV4cCI6MTY5MDE0MzQyOX0.tFWWbsGViCACPEDwdPCXqy4Qcqsrh7mWx7XLVIYQkhQ",
#   "username": "zai",
#   "userID": "64b42f34032d7956c713bb85"
# }

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NGI0NTBjYTVjMTY1ZTU1NTQ2Y2EwNmMiLCJpYXQiOjE2ODk1Mzg3OTMsImV4cCI6MTY5MDE0MzU5M30.KkiBhNFn9YLFbCj31ZaGtaAgLIqVWvF8kY8gO3Ee52U",
  "username": "teto",
  "userID": "64b450ca5c165e55546ca06c"
}