# Create a Summary
PATCH http://localhost:5000/todolist/647fd41de2b29b53b45d175d
Content-Type: application/json

{
  "completed": true,
  "completedDate": "2023-06-08T12:00:00Z"
}

###
GET http://localhost:5000/todolist/

# Get a Summary by ID
GET http://localhost:5000/goals/summaries/64725360f778401d7d6d2dde
# Replace `:id` with the actual ID of the goals/summaries entry you want to retrieve.

###64a2b1922cf985a572b52ac2
POST http://localhost:5000/register/
Content-Type: application/json

{
    "username":"zai",
    "email":"zai@gmail.com",
    "password":"123"
}
###
POST http://localhost:5000/login/username
Content-Type: application/json

{
    "username":"zai",
    "password":"123"
}
###
POST http://localhost:5000/login/email
Content-Type: application/json

{
    "email":"zai@gmail.com",
    "password":"123"
}


# Replace `:id` with the actual ID of the goals/summaries entry you want to update.

###
DELETE http://localhost:5000/todolist/6470f97d394250fcd9a23e00
# Replace `:id` with the actual ID of the summary you want to delete.
